### ISSUE TITLE
commandline: path to config

### ISSUE THREAD

**Issue by Inveracity** [lemonsaurus/blackbox#33]
Add commandline functionality to specify a path to a config

```sh
blackbox --config=path/to/config.yml
```

and of course have a sensible default

**Comment by lemonsaurus** [comment]
This is blocked by #31, the way it's currently specified, but I need a solution to this very soon, since it's blocking deployment for python-discord. For kubernetes, I can't put files into the root folder easily with volume mounts, I need to put them in subdirectories.

Here are two approaches I'm considering:

## Just rglob the whole folder looking for the config file.
We could just make the config parser use pathlibs excellent `.rglob` to recursively search through every folder (except maybe .venv) looking for something like `blackbox.yaml`. Then, if it finds it, use that. That way, the user can put the file anywhere they want inside the blackbox folder and it'll work fine.

## Allow an environment variable to specify the path
We could implement this as an environment variable at first, and then later we can add the commandline flag as well.

**Comment by lemonsaurus** [comment]
the rglob idea is more fun, but I don't know if it's useful. the rglob method does not allow you to configure a path outside the `/blackbox` folder, which may be useful.

Let's just implement an env var that it will respect for now, and then we can extend that method to a flag for the CLI tool later.
